### PR TITLE
Fixes disappearing cursor on external display

### PR DESCRIPTION
**Pull request by men232**
#29 #24

### CODE REVIEW

**Comment by citypaul** [comment]
@Stengo if this is good, any chance of a merge and a release? It will fix a key issue in the latest version of macOS.

**Comment by farshid3003** [comment]
Could you please merge this and create a new version??? This is a big issue.

**Comment by Stengo** [comment]
Amazing work, thank you so much for looking into this! I will create a release right after merging this 🎉

**Comment by citypaul** [comment]
Great stuff, thanks @Stengo and especially to @men232 for the fix!

**Pull request merged**
